### ISSUE TITLE
Stops after updating rebalances and prices

### ISSUE THREAD

**Issue by gdog9093** [arnav-ag/exchange_frontrun#1]
I am struggling to get this to work I think, unless if I am mistaken. I run the script and it successfully updates rebalances and prices but then doesn't do anything as if it is frozen but I don't think it is. I am going to try running with pm2 to see if there are any hidden errors I am not seeing.

**Comment by arnav-ag** [comment]
It only shows you something if there's something that goes over the threshold! You can play with that value (set it to 0.01) and make sure you see the connected to web socket message 😀
