### ISSUE TITLE
RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by ZakatZakat** [arnav-ag/exchange_frontrun#2]
Got this error:

asyncio.run(multi_thread_this())

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by arnav-ag** [comment]
I believe this is an error if you're using a version of Python lower than 3.7! I'm using Python3.11 locally and it gives no errors. Do try to update your Python version and let me know the results.

**Comment by ZakatZakat** [comment]
Yes, thank you: I've updated my python to 3.11 and now it works fine (my previous python version was 3.10.9).
